In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('datasets/salary_data_cleaned.csv')

In [4]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,...,Revenue,hourly,salary,company_txt,age,python_yn,spark_yn,aws_yn,excel_yn,communication_yn
0,Data Scientist,"$135,000 /yr (est.)",Overview\nOur client is seeking experienced Da...,-1.0,Interpro People,Sydney,-1,-1,-1,-1,...,-1,0,135000.0,Interpro Peo,-1,0,0,0,0,0
1,Data Quality Scientist,"$112,729 /yr (est.)",SYNOPSIS:\nData Quality Scientist\n\n\nApplica...,4.3,Geoscience Australia\n4.3,Canberra,501 to 1000 Employees,2001,Government,National Services & Agencies,...,$100 to $500 million (USD),0,112729.0,Geoscience Australia\n,21,0,0,0,0,0
2,Senior Data Scientist x 2,"$146,990 /yr (est.)",Organisation/Entity: Transport For NSW\nJob Ca...,3.7,NSW Government -Transport For NSW\n3.7,Sydney,501 to 1000 Employees,-1,Contract,-1,...,Unknown / Non-Applicable,0,146990.0,NSW Government -Transport For NSW\n,-1,0,0,0,0,0
3,Data Scientist,"$125,000 /yr (est.)",Job description\nData Scientist Skills\nProgra...,-1.0,GoTech Solutions Pty Ltd,Sydney,Unknown,-1,Company - Public,-1,...,Unknown / Non-Applicable,0,125000.0,GoTech Solutions Pty,-1,1,0,0,0,0
4,Earth Observation Data Scientist,"$94,842 /yr (est.)",SYNOPSIS:\nEarth Observation Data Scientist\n\...,4.3,Geoscience Australia\n4.3,Canberra,501 to 1000 Employees,2001,Government,National Services & Agencies,...,$100 to $500 million (USD),0,94842.0,Geoscience Australia\n,21,0,0,0,0,0

In [5]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'hourly', 'salary', 'company_txt',
       'age', 'python_yn', 'spark_yn', 'aws_yn', 'excel_yn',
       'communication_yn'],
      dtype='object')